# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addBook.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

class AddBookPage(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(800, 600)
        Dialog.setStyleSheet("background-color: rgb(202, 215, 239);")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(130, 80, 521, 401))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.titleAddBook = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.titleAddBook.setFont(font)
        self.titleAddBook.setAlignment(QtCore.Qt.AlignCenter)
        self.titleAddBook.setObjectName("titleAddBook")
        self.verticalLayout_3.addWidget(self.titleAddBook)
        self.labelInfo = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.labelInfo.setFont(font)
        self.labelInfo.setAlignment(QtCore.Qt.AlignCenter)
        self.labelInfo.setObjectName("labelInfo")
        self.verticalLayout_3.addWidget(self.labelInfo)
        spacerItem = QtWidgets.QSpacerItem(20, 50, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.titleInput = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.titleInput.setFont(font)
        self.titleInput.setStyleSheet("background-color: rgb(255,255,255)")
        self.titleInput.setText("")
        self.titleInput.setObjectName("titleInput")
        self.verticalLayout.addWidget(self.titleInput)
        self.editorInput = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.editorInput.setFont(font)
        self.editorInput.setStyleSheet("background-color: rgb(255,255,255)")
        self.editorInput.setText("")
        self.editorInput.setObjectName("editorInput")
        self.verticalLayout.addWidget(self.editorInput)
        self.coverColorInput = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.coverColorInput.setFont(font)
        self.coverColorInput.setStyleSheet("background-color: rgb(255,255,255)")
        self.coverColorInput.setText("")
        self.coverColorInput.setObjectName("coverColorInput")
        self.verticalLayout.addWidget(self.coverColorInput)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.labelPublicationDate = QtWidgets.QLabel(self.layoutWidget)
        self.labelPublicationDate.setStyleSheet("background-color: rgb(255,255,255);\n"
"color: rgb(119, 119, 119);")
        self.labelPublicationDate.setObjectName("labelPublicationDate")
        self.horizontalLayout_4.addWidget(self.labelPublicationDate)
        self.dateEdit = QtWidgets.QDateEdit(self.layoutWidget)
        self.dateEdit.setStyleSheet("background-color: rgb(255,255,255)")
        self.dateEdit.setDate(QtCore.QDate(2020, 1, 1))
        self.dateEdit.setObjectName("dateEdit")
        self.horizontalLayout_4.addWidget(self.dateEdit)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.authorInput = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.authorInput.setFont(font)
        self.authorInput.setStyleSheet("background-color: rgb(255,255,255)")
        self.authorInput.setText("")
        self.authorInput.setObjectName("authorInput")
        self.verticalLayout_2.addWidget(self.authorInput)
        self.continentInput = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.continentInput.setFont(font)
        self.continentInput.setStyleSheet("background-color: rgb(255,255,255)")
        self.continentInput.setText("")
        self.continentInput.setObjectName("continentInput")
        self.verticalLayout_2.addWidget(self.continentInput)
        self.nationalityInput = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.nationalityInput.setFont(font)
        self.nationalityInput.setStyleSheet("background-color: rgb(255,255,255)")
        self.nationalityInput.setText("")
        self.nationalityInput.setObjectName("nationalityInput")
        self.verticalLayout_2.addWidget(self.nationalityInput)
        self.readInput = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(25)
        self.readInput.setFont(font)
        self.readInput.setStyleSheet("background-color: rgb(255,255,255)")
        self.readInput.setText("")
        self.readInput.setObjectName("readInput")
        self.verticalLayout_2.addWidget(self.readInput)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        spacerItem1 = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.cancelButton = QtWidgets.QPushButton(self.layoutWidget)
        self.cancelButton.setMinimumSize(QtCore.QSize(100, 30))
        self.cancelButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancelButton.setStyleSheet("background-color: rgb(246, 156, 167)")
        self.cancelButton.setObjectName("cancelButton")
        self.horizontalLayout_2.addWidget(self.cancelButton)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.addButton = QtWidgets.QPushButton(self.layoutWidget)
        self.addButton.setMinimumSize(QtCore.QSize(100, 30))
        self.addButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addButton.setStyleSheet("background-color: rgb(137, 255, 128)")
        self.addButton.setObjectName("addButton")
        self.horizontalLayout_2.addWidget(self.addButton)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem4)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Add Book"))
        self.titleAddBook.setText(_translate("Dialog", "ADD BOOK"))
        self.labelInfo.setText(_translate("Dialog", "Please input the book\'s information"))
        self.titleInput.setPlaceholderText(_translate("Dialog", "TITLE"))
        self.editorInput.setPlaceholderText(_translate("Dialog", "EDITOR"))
        self.coverColorInput.setPlaceholderText(_translate("Dialog", "COVER COLOR"))
        self.labelPublicationDate.setText(_translate("Dialog", "PUBLICATION DATE:"))
        self.authorInput.setPlaceholderText(_translate("Dialog", "AUTHOR"))
        self.continentInput.setPlaceholderText(_translate("Dialog", "CONTINENT"))
        self.nationalityInput.setPlaceholderText(_translate("Dialog", "NATIONALITY"))
        self.readInput.setPlaceholderText(_translate("Dialog", "# OF TIMES READ"))
        self.cancelButton.setText(_translate("Dialog", "CANCEL"))
        self.addButton.setText(_translate("Dialog", "ADD"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
