# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'homeScreen.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(1100, 700)
        MainWindow.setMouseTracking(False)
        MainWindow.setAutoFillBackground(False)
        MainWindow.setStyleSheet("background-color: rgb(204, 218, 238)")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(50, 10, 1004, 581))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.addBookButton = QtWidgets.QPushButton(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.addBookButton.setFont(font)
        self.addBookButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.addBookButton.setStyleSheet("background-color: rgb(126, 255, 145)")
        self.addBookButton.setObjectName("addBookButton")
        self.verticalLayout.addWidget(self.addBookButton)
        self.removeBookButton = QtWidgets.QPushButton(self.layoutWidget)
        self.removeBookButton.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(22)
        self.removeBookButton.setFont(font)
        self.removeBookButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.removeBookButton.setStyleSheet("background-color: rgb(255, 165, 173)")
        self.removeBookButton.setObjectName("removeBookButton")
        self.verticalLayout.addWidget(self.removeBookButton)
        self.horizontalLayout.addLayout(self.verticalLayout)
        spacerItem = QtWidgets.QSpacerItem(100, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.allBooksTitle = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.allBooksTitle.setFont(font)
        self.allBooksTitle.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.allBooksTitle.setAlignment(QtCore.Qt.AlignCenter)
        self.allBooksTitle.setObjectName("allBooksTitle")
        self.horizontalLayout.addWidget(self.allBooksTitle)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.searchField = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.searchField.setFont(font)
        self.searchField.setStyleSheet("background-color: rgb(255,255,255);\n"
"border: 1px solid black;")
        self.searchField.setText("")
        self.searchField.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.searchField.setObjectName("searchField")
        self.horizontalLayout.addWidget(self.searchField)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.tableBooks = QtWidgets.QTableWidget(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableBooks.sizePolicy().hasHeightForWidth())
        self.tableBooks.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.tableBooks.setFont(font)
        self.tableBooks.setMouseTracking(True)
        self.tableBooks.setStyleSheet("background-color: rgb(255, 255, 255)")
        self.tableBooks.setAlternatingRowColors(True)
        self.tableBooks.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectItems)
        self.tableBooks.setCornerButtonEnabled(True)
        self.tableBooks.setRowCount(30)
        self.tableBooks.setObjectName("tableBooks")
        self.tableBooks.setColumnCount(8)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(12)
        item.setFont(font)
        self.tableBooks.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableBooks.setHorizontalHeaderItem(7, item)
        self.tableBooks.horizontalHeader().setVisible(True)
        self.tableBooks.horizontalHeader().setCascadingSectionResizes(True)
        self.tableBooks.horizontalHeader().setDefaultSectionSize(123)
        self.tableBooks.horizontalHeader().setHighlightSections(True)
        self.tableBooks.horizontalHeader().setMinimumSectionSize(15)
        self.tableBooks.horizontalHeader().setSortIndicatorShown(True)
        self.tableBooks.horizontalHeader().setStretchLastSection(True)
        self.tableBooks.verticalHeader().setVisible(True)
        self.tableBooks.verticalHeader().setCascadingSectionResizes(False)
        self.verticalLayout_2.addWidget(self.tableBooks)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.revertChangeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.revertChangeButton.setEnabled(False)
        self.revertChangeButton.setMinimumSize(QtCore.QSize(175, 44))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.revertChangeButton.setFont(font)
        self.revertChangeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.revertChangeButton.setStyleSheet("background-color: rgb(255, 165, 173);\n"
"")
        self.revertChangeButton.setObjectName("revertChangeButton")
        self.horizontalLayout_2.addWidget(self.revertChangeButton)
        spacerItem3 = QtWidgets.QSpacerItem(10, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem3)
        self.saveChangeButton = QtWidgets.QPushButton(self.layoutWidget)
        self.saveChangeButton.setEnabled(False)
        self.saveChangeButton.setMinimumSize(QtCore.QSize(175, 44))
        font = QtGui.QFont()
        font.setPointSize(30)
        self.saveChangeButton.setFont(font)
        self.saveChangeButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.saveChangeButton.setStyleSheet("background-color: rgb(126, 255, 145)")
        self.saveChangeButton.setObjectName("saveChangeButton")
        self.horizontalLayout_2.addWidget(self.saveChangeButton)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1100, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Home Page - All books"))
        self.addBookButton.setText(_translate("MainWindow", "ADD BOOK"))
        self.removeBookButton.setText(_translate("MainWindow", "REMOVE BOOK"))
        self.allBooksTitle.setText(_translate("MainWindow", "Book Inventory"))
        self.searchField.setPlaceholderText(_translate("MainWindow", "Search"))
        self.tableBooks.setSortingEnabled(True)
        item = self.tableBooks.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableBooks.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableBooks.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableBooks.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableBooks.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableBooks.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableBooks.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableBooks.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        item = self.tableBooks.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "9"))
        item = self.tableBooks.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Title"))
        item = self.tableBooks.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Author"))
        item = self.tableBooks.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Editor"))
        item = self.tableBooks.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Nationality"))
        item = self.tableBooks.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Continent"))
        item = self.tableBooks.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "Published date"))
        item = self.tableBooks.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "Cover color"))
        item = self.tableBooks.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "# of times read"))
        self.revertChangeButton.setText(_translate("MainWindow", "Revert change"))
        self.saveChangeButton.setText(_translate("MainWindow", "Save change"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
