# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'registerPage.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

class RegisterPage(QDialog):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.WindowModal)
        Dialog.resize(800, 600)
        Dialog.setStyleSheet("background-color: rgb(202, 215, 239);")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(260, 120, 287, 310))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.registerTitleLabel = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(50)
        self.registerTitleLabel.setFont(font)
        self.registerTitleLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.registerTitleLabel.setObjectName("registerTitleLabel")
        self.verticalLayout.addWidget(self.registerTitleLabel)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.emailInput = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.emailInput.setFont(font)
        self.emailInput.setStyleSheet("background-color: rgb(255,255,255)")
        self.emailInput.setObjectName("emailInput")
        self.verticalLayout.addWidget(self.emailInput)
        self.usernameInput = QtWidgets.QLineEdit(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.usernameInput.setFont(font)
        self.usernameInput.setStyleSheet("background-color: rgb(255,255,255)")
        self.usernameInput.setObjectName("usernameInput")
        self.verticalLayout.addWidget(self.usernameInput)
        self.passwordInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.passwordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.passwordInput.setFont(font)
        self.passwordInput.setStyleSheet("background-color: rgb(255,255,255)")
        self.passwordInput.setObjectName("passwordInput")
        self.verticalLayout.addWidget(self.passwordInput)
        self.verifyPasswordInput = QtWidgets.QLineEdit(self.layoutWidget)
        self.verifyPasswordInput.setEchoMode(QtWidgets.QLineEdit.Password)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.verifyPasswordInput.setFont(font)
        self.verifyPasswordInput.setStyleSheet("background-color: rgb(255,255,255)")
        self.verifyPasswordInput.setObjectName("verifyPasswordInput")
        self.verticalLayout.addWidget(self.verifyPasswordInput)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.registerButton = QtWidgets.QPushButton(self.layoutWidget)
        self.registerButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.registerButton.setStyleSheet("background-color: rgb(137, 255, 128)")
        self.registerButton.setObjectName("registerButton")
        self.verticalLayout.addWidget(self.registerButton)
        self.exitButton = QtWidgets.QPushButton(self.layoutWidget)
        self.exitButton.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.exitButton.setStyleSheet("background-color: rgb(246, 156, 167)")
        self.exitButton.setObjectName("exitButton")
        self.verticalLayout.addWidget(self.exitButton)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 200, 231, 131))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.warningEmail = QtWidgets.QLabel(self.layoutWidget1)
        self.warningEmail.setEnabled(False)
        self.warningEmail.setStyleSheet("color: rgb(202, 215, 239);")
        self.warningEmail.setAlignment(QtCore.Qt.AlignCenter)
        self.warningEmail.setWordWrap(True)
        self.warningEmail.setObjectName("warningEmail")
        self.verticalLayout_2.addWidget(self.warningEmail)
        self.warningUsername = QtWidgets.QLabel(self.layoutWidget1)
        self.warningUsername.setStyleSheet("color: rgb(202, 215, 239);")
        self.warningUsername.setAlignment(QtCore.Qt.AlignCenter)
        self.warningUsername.setWordWrap(True)
        self.warningUsername.setObjectName("warningUsername")
        self.verticalLayout_2.addWidget(self.warningUsername)
        self.warningPassword = QtWidgets.QLabel(self.layoutWidget1)
        self.warningPassword.setStyleSheet("color: rgb(202, 215, 239);")
        self.warningPassword.setAlignment(QtCore.Qt.AlignCenter)
        self.warningPassword.setWordWrap(True)
        self.warningPassword.setObjectName("warningPassword")
        self.verticalLayout_2.addWidget(self.warningPassword)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.registerTitleLabel.setText(_translate("Dialog", "Register"))
        self.emailInput.setPlaceholderText(_translate("Dialog", "Email"))
        self.usernameInput.setPlaceholderText(_translate("Dialog", "Username"))
        self.passwordInput.setPlaceholderText(_translate("Dialog", "Password"))
        self.verifyPasswordInput.setPlaceholderText(_translate("Dialog", "Verify Password"))
        self.registerButton.setText(_translate("Dialog", "Register"))
        self.exitButton.setText(_translate("Dialog", "Exit"))
        self.warningEmail.setText(_translate("Dialog", "Email must include an \"@\""))
        self.warningUsername.setText(_translate("Dialog", "Username must consist of letters and be greater than 5 characters"))
        self.warningPassword.setText(_translate("Dialog", "\"Password\" and \"Verify Password\" must be equal"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
